# Generated by Django 5.0 on 2024-11-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_workflow_document_file_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='workflows',
            field=models.ManyToManyField(blank=True, null=True, related_name='documents', to='documents.workflow'),
        ),
    ]
